### ISSUE TITLE
Crash on Enable Lockstep

### ISSUE THREAD

**Issue by Oktrako** [zaren171/RepliShot#2] opened 2022-04-24 23:53 UTC
I'm trying to get a this working with a fairly old laptop and it appears to be fully functional other than crashing when enabling lockstep (arguably the best QoL feature). Originally the program was not working at all on this laptop until windows 10 was installed (was originally windows 7 still). Computer as an old acer aspire with an i3 380m and 4gb of ram. As I said all other options and functionality appears to work.

**Comment by zaren171** [comment] 2022-04-27 02:12
The algorithm for the lock step (Tesseract) is quite a beast.  I'm not sure exactly why it would cause a crash, as the call is in a loop, so each call should be separated by a sleep.  I could see overlapping calls causing the crash.  Anyway, I am considering putting in a selectable delay between tesseract calls in the next update.  I don't know that this would fix the issue, but I hope so.  Does your old laptop run TGC well?  TGC 2019 doesn't work well on my laptops, and it sounds like they're a bit newer/more powerful (i5 630m).  I could also see the issue being running both TGC and the tesseract functions at the same time.  I haven't really monitored the memory usage of Replishot, but I would thing TGC would be eating most of your 4gb.

**Comment by Oktrako** [comment] 2022-04-27 02:40
Interesting. I was looking at the Event Logs after I posted this and it appears to be giving error 0xc000001d. It may be that the compiled code, due to being compiled on a newer machine, is calling an instruction that old processor can't handle. 

I'm actually running TGC 2019 on my gaming desktop and using steam remote play to steam it to the laptop. It appears that the rest of replishot is functioning with such a setup. 

The ram being eaten up might be an idea though so I'll check that out as well.

**Comment by zaren171** [comment] 2022-04-27 13:51
Does the program die at a consistent time, or does it sometimes run longer than others?  

I searched the error code online, and the top hits said it may be caused by software that incorrectly installed/uninstalled and left windows system files in a bad state.  Replishot doesn't install/modify anything when it runs, but it does use a wide range of Windows libraries, so if any of these are altered or missing on your local machine that could be the issue.  It also seems the problem is centered around Tesseract, and seeing as that's a 3rd party library I am using I have no clue what Windows system functionality it is using.

As for Steam remote play, I use that too.  I've noticed that not all of the controls feed through properly, not all of Replishot's keyboard presses pass through.  I won't go into details here, but I'm working on a network mode that I believe should fix this issue (though in my mind I'd also stop using Steam remote play, and use something like TeamViewer to see the remote desktop.)  Anyway, a bit off topic for this thread.

**Comment by Oktrako** [comment] 2022-04-27 16:42
The Behavior appears to be that it runs for a second after checking the box and then the program stop responding before crashing. It is possible a library is required as I have plenty installed on my gaming desktop from programming, On the laptop is a mostly vanilla windows 10 install on the laptop (with the exception of ensuring .net 3.5 and 4.8 are installed).

I'll test out an sfc /scannow to check for system file errors and take a look at the RAM usage as well.

**Comment by zaren171** [comment] 2022-08-25 18:55
I'm closing this issue as the lockstep uses a completely new algorithm, so tesseract and the potential issues associated with it no longer apply.  If a new crash is found it should be reported separately.

**Closed as completed by zaren171** 2022-08-25 18:55 UTC
