### ISSUE TITLE
Replishot for GSPro

### ISSUE THREAD

**Issue by csites** [zaren171/RepliShot#3] opened 2022-07-12 21:35 UTC
Hi Zaren.  I tried to send you a private message on the golfsimulatorforum about an idea to rework a version of replishot for the GSPro golf simulation software.   Funny thing though, whenever I typed in 'gspro' my messages were blocked by the moderators.   Anyway, gspro is a fairly nre new golfsim software and has an openAPI that can be coded to make it work with DIY Launch monitor.   It's being used by garmin, skytrack, and others with software source here on github.  Just search 'gspro' and you'll find them.  It might be worth a look at.   

So no issue here; Just a feature request to consider.  I'm a systems programmer and do golf to chill, so when I saw your code in the optishot section on golfsimulatorforum, I just thought that was the coolest thing.  

Have fun, 
Chuck.

**Comment by zaren171** [comment] 2022-08-25 19:00
Not an actually issue, so closing.  The scope of this project is to connect an Optishot with TGC2019.  As I've worked on this code the idea of creating a generic golf sim bridge has buzzed around my head, with code that gathers data from various launch monitors (Optishot, Mevo+, R10, Trakman, etc.) processes data from the selected source, and then feeds it out to the desired destination (E6, TGC, GSPro, etc.) doing whatever processing is required to get there.  It would sort of be a "super" replishot, and through community development would hopefully get to the point where it took data from just about any source, and allowed it to be played on just about any destination.  Anyway, that's not this project, but maybe something I look into in the future.

**Closed as completed by zaren171** 2022-08-25 19:00 UTC

**Comment by csites** [comment] 2022-08-25 20:01
HI Zaren,

   Yeah, the funny thing about the golfsimulatorforum.com;  apparently just
mentioning the word 'GSPRO' will get you banned from the forum.  Haha.
They accused some GSPRO developers of spying on TGC devs and borrowing
ideas.  So I really don't know of the validity.  The only way I know about
that is after getting banned, I did a little googling which took me to a
Reddit forum where someone else got the boot for mentioning gspro.  Funny.
I thought about the same thing several times.  I think your solution to get
TGC2019 running on Optishot on the cheap is just about one of the coolest
ideas, turning a club swing into a lot of keyboard moves and having it
actually work!   I can imagine the patience and time it took to get it
working, and working well.    GSpro is an easy target with the openAPI
interface.

I recently bought a Garmin R10 and GSpro, and started using a middleware
piece that translates shotdata meant for E6 into the openAPI and feed to
GSPro.  (they wrote It in Javascript and it's opensource.  It's on GitHub,
just search for gspro and look for something like R10-to-gspro-v2.  It's a
kludge, but it works well, although you need to phone app to translate R10
to E6 in the first place.  To go directly to the openAPI formate from just
the club data (or in my case, I've wanted to get the data from the TittleX
unit), there is some math to do.   Namely, you would need to go calculate
back spin and side spin from the club face angle(s),  Also the way the club
is used (wedge, vs, irons, vs hybrids and woods, vs putter). There is a
engineer/owner that runs GSAgolf.com that build camera based simulators,
and he has on his site a detailed tutorial of the math used to go from club
speed to all the parameters of ball flight.  To derive all of that (it is
pretty hairy geometry) would be to use some symbolic computer algebra
system like Maxima.   To get real fancy, do what Gamin does with the R0 and
use machine learning to get all of the chips, flops, and blades modeled
correctly.    Anyway, something to ponder on.

https://golf-simulators.com/physics.htm

Anyway, have fun.   I've enjoyed your code immensely.    Best regards,
Chuck (aka CB on discord).

**Comment by Richardmyno** [comment] 2024-12-22 16:43
This is very interesting. Ive got a OS2, and I just want to play for fun, but with okay-ish data. Not sure to what extent you can expect for the data OS2 is Reading, but using some complex math to do estimations of spin etc would be cool!
Havent looked too much into the openapi for GSPro, but would be cool to try and see if its possible to integrate it somehow.
Anyways, thanks so much for this! Will test it out asap

**Comment by zaren171** [comment] 2025-01-09 19:39
the problem is how limited the data from the optishot is.  The optishot has 2 rows of infrared leds with sensors.  When the club passes over the top of the light, the sensor detects the light that is reflected back down.  The sensor "triggers" and a timestamp is saved.  The only information the optishot can provide is a set of points in a 2d plane, and what time they saw something above them.  Using this you can get an idea of how the club is passing over each strip, and then guess at what the head is doing in the middle.  The real downside here is that in all this, there is no indication of where the ball is located, or how high the ball or club is.  The optishot software freely admits this in the fact that you can select between 5 lofts for how your shot should leave the club.  Spin numbers wouldn't mean anything because we don't know where the ball is and how it was struck.  The only path on this would be to look at a bunch of data from other launch monitors that track the ball, and then create some equation to fill in the in-between points of the data.  To be honest, with how the optishot performs, you could grab this data from PGA tour data sets.  That data is unlikely to align with a typical user, and so, the spin data wouldn't really mean anything.  Heck, the curve left/right from side spin doesn't really mean anything in Optishot or in replishot, and both have a maximum which provides leniency on shots that would hook way off to the side.  It's just the limitation of the optishot.

**Comment by csites** [comment] 2025-01-09 23:19
Hi Zaren171.   I think the idea would be to build an OpenAPI server for the
TGC2019 game.   The OpenAPI 'server' in GSPro is hosted by the game.   The
Launch Monitor would provide the OpenAPI connector.     The OpenAPI just
basically exchanges a JSON between the LM and the API server.  So the idea
would be to replace the Optishot translator with something more general
like OpenAPI JSON data to your incredible TGC key translator used for the
Optishot.  That would generalize the LM thing for the TGC2019 game and make
it accessible to many LMs that currently are not supported in that game.
I wrote an OpenAPI server in Python for testing and it's pretty
straightforward and its on my GitHub.    So this plan would be build an
OpenAPI server that takes data from various launch monitors and translates
the LM data into the keystroke feed of TGC2019 or later game course systems.


Best regards,
Chuck
